// GENERATED by scripts/lean_to_verus.py -- DO NOT EDIT.
//
// Every function below is a mechanical transliteration of a definition in
// Dpss/FenceInt.lean, cited by file and line above each one. Regenerate with
//
//     python3 scripts/lean_to_verus.py
//
// CI regenerates and fails if this file has drifted, so it cannot silently rot.
//
// These are the predicates that never execute, so nothing but this generator
// checks that the Verus ones say what the Lean ones say. The `_ex` functions of
// ../fence.rs are proved to compute them (S6b); this file is where they come
// from (S6d).
//
// No scaling argument is involved, unlike the team model: `Dpss/FenceInt.lean`
// states the fence over the same integers Verus has.
//
// What is deliberately NOT generated: `trajOk`, which quantifies over every
// sample -- the same exclusion the team model makes for its standing conditions
// -- and the `Vehicle` struct itself, which is hand-written in ../vehicle.rs as
// `Dir` and `Snapshot` are. `traj_ok` is assembled from `obs_ok`, `fence_dir` and
// `leg_ok` in ../fence.rs, so the predicates a wrong transcription would hide in
// are all below.

use vstd::prelude::*;
use crate::dir::Dir;
use crate::vehicle::Vehicle;

verus! {

/// `DPSS.FenceInt.Vehicle.wf` -- Dpss/FenceInt.lean:65
pub open spec fn wf(v: Vehicle) -> bool {
    (((0 <= v.dmax) && (0 <= v.turn)) && (0 <= v.eps))
}
/// `DPSS.FenceInt.Vehicle.clearance` -- Dpss/FenceInt.lean:71
pub open spec fn clearance(v: Vehicle, d: Dir) -> int {
    if (d == Dir::Left) { (v.dmax + v.turn) } else { v.turn }
}
/// `DPSS.FenceInt.fenceDir` -- Dpss/FenceInt.lean:102
pub open spec fn fence_dir(margin: int, phat: int, req: Dir) -> Dir {
    if (phat <= margin) { Dir::Right } else { req }
}
/// `DPSS.FenceInt.safe` -- Dpss/FenceInt.lean:109
pub open spec fn safe(v: Vehicle, p: int, d: Dir) -> bool {
    (clearance(v, d) <= p)
}
/// `DPSS.FenceInt.legOk` -- Dpss/FenceInt.lean:115
pub open spec fn leg_ok(v: Vehicle, p: int, d: Dir, low: int, p_next: int) -> bool {
    (((((low <= p) && (low <= p_next)) && (((d == Dir::Left) ==> ((p - v.dmax) <= low)))) && (((d == Dir::Right) ==> ((p - v.turn) <= low)))) && (((d == Dir::Right) ==> (p <= p_next))))
}
/// `DPSS.FenceInt.obsOk` -- Dpss/FenceInt.lean:125
pub open spec fn obs_ok(v: Vehicle, obs: int, p: int) -> bool {
    (((-v.eps) <= (obs - p)) && ((obs - p) <= v.eps))
}
} // verus!
