// GENERATED by scripts/lean_to_verus.py -- DO NOT EDIT.
//
// Every function below is a mechanical transliteration of a definition in
// Dpss/SeparationInt.lean, cited by file and line above each one. Regenerate with
//
//     python3 scripts/lean_to_verus.py
//
// CI regenerates and fails if this file has drifted, so it cannot silently rot.
//
// The pair and the link, at the same integers as the fence. Every predicate here
// is proved in Lean to be the corresponding fence predicate on the doubled
// vehicle (`pairLegOk_iff` and friends), which is the content of
// `PairTraj.toFence` -- the pair layer adds coordinates, not content.
// What is deliberately NOT generated: `link_ok`'s two index clauses. Both
// subtract sample indices, which in Lean is ℕ subtraction (truncating at zero)
// and in Verus is `int` subtraction (not). They agree under the `src(k) <= k`
// that `link_ok` itself states -- but a translator that mapped one to the other
// would be unsound in general, and this one refuses rather than guesses. They
// are hand-written in ../comms.rs, beside the Lean statement in
// `DPSS.Fence.CommsPair`.

use vstd::prelude::*;
use crate::dir::Dir;
use crate::vehicle::Vehicle;
use crate::spec::fence_model::*;

verus! {

/// `DPSS.FenceInt.pairVehicle` -- Dpss/SeparationInt.lean:50
pub open spec fn pair_vehicle(v: Vehicle) -> Vehicle {
    Vehicle { dmax: (2 * v.dmax), turn: (2 * v.turn), eps: (2 * v.eps) }
}
/// `DPSS.FenceInt.commsPairVehicle` -- Dpss/SeparationInt.lean:54
pub open spec fn comms_pair_vehicle(v: Vehicle, a: nat) -> Vehicle {
    Vehicle { dmax: (2 * v.dmax), turn: (2 * v.turn), eps: ((2 * v.eps) + ((a) * v.dmax)) }
}
/// `DPSS.FenceInt.pairObsOk` -- Dpss/SeparationInt.lean:95
pub open spec fn pair_obs_ok(v: Vehicle, obs: int, g: int) -> bool {
    (((-((2 * v.eps))) <= (obs - g)) && ((obs - g) <= (2 * v.eps)))
}
/// `DPSS.FenceInt.pairLegOk` -- Dpss/SeparationInt.lean:101
pub open spec fn pair_leg_ok(v: Vehicle, g: int, m: Dir, low: int, g_next: int) -> bool {
    (((((low <= g) && (low <= g_next)) && (((m == Dir::Left) ==> ((g - (2 * v.dmax)) <= low)))) && (((m == Dir::Right) ==> ((g - (2 * v.turn)) <= low)))) && (((m == Dir::Right) ==> (g <= g_next))))
}
/// `DPSS.FenceInt.pairSafe` -- Dpss/SeparationInt.lean:109
pub open spec fn pair_safe(v: Vehicle, d: int, g: int, m: Dir) -> bool {
    ((d + clearance((pair_vehicle(v)), m)) <= g)
}
/// `DPSS.FenceInt.pairTrajStepOk` -- Dpss/SeparationInt.lean:113
pub open spec fn pair_traj_step_ok(v: Vehicle, d: int, margin: int, g: int, m: Dir, low: int, obs: int, req: Dir, g_next: int) -> bool {
    ((pair_obs_ok(v, obs, g) && (m == fence_dir(margin, ((obs - d)), req))) && pair_leg_ok(v, g, m, low, g_next))
}
/// `DPSS.FenceInt.commsStepOk` -- Dpss/SeparationInt.lean:125
pub open spec fn comms_step_ok(v: Vehicle, a: nat, d: int, margin: int, g: int, obs: int, m: Dir, low: int, req: Dir, g_next: int) -> bool {
    (((((-(((2 * v.eps) + ((a) * v.dmax)))) <= (obs - g)) && ((obs - g) <= ((2 * v.eps) + ((a) * v.dmax)))) && (m == fence_dir(margin, ((obs - d)), req))) && pair_leg_ok(v, g, m, low, g_next))
}
} // verus!
