#!/usr/bin/env python3
"""Generate the Verus specification from Lean.

The Rust half must be checked against *the* specification, not against a second
one that somebody typed in again. So the scalar and boolean definitions of the
integer model are translated mechanically into Verus `spec fn`s, and the result is
checked in and re-generated by CI, which fails if it has drifted.

## What this is, and what it is not

It is a translator for **one file**, over a deliberately small grammar. It is not a
general Lean front end and must never be mistaken for one. Anything outside the
grammar is **refused with an error naming the definition and the token**, never
guessed at — a translator that quietly does its best is worse than no translator,
because the Rust would then verify beautifully against the wrong specification.

It is also *syntactic only*. The one semantically interesting step in this port —
real numbers to integers — happens in `Dpss/IntModel.lean`, where it is proved
(`embed_step`, `intRun_converges`). This script only changes notation.

## What it does not translate, and why

Four kinds of definition are hand-written on the Rust side instead, each citing its
Lean source:

* `advance`, `step`, `run` build a new configuration — structure literals and
  recursion, not arithmetic;
* `timeToNextEvent` is a `Finset.inf'` over `Fin n`;
* `OnPerimeter`, `AdjOrdered`, `EscortsCoherent`, `OnLattice` quantify over `Fin n`
  with a dependent proof argument;
* `Dir` itself is a Rust `enum`.

None of those is arithmetic, which is where a transcription error would hide. The
differential tests cover them end to end.

## Two sources, two shapes

`Dpss/IntModel.lean` describes the **team**, and every definition in it is a
function of the configuration: the translator supplies `c: Snapshot` and, where
the Lean takes a `Fin n`, an `i: int`.

`Dpss/FenceInt.lean` describes **one drone against one wall** (S6a), and its
definitions take their arguments explicitly — a vehicle, a position, a heading.
So the translator reads the binders and emits them, and the grammar carries the
propositional connectives that the safety predicates are built from: `∧`, `∨`,
`¬` and `→` become `&&`, `||`, `!` and `==>`.

The two shapes are `SOURCES` below. Everything else — the tokenizer, the
expression grammar, and the refusal discipline — is shared.

Usage: python3 scripts/lean_to_verus.py [--check]
"""
from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------
# What to translate, in dependency order. A name not listed here is not emitted;
# a name listed here that cannot be parsed is a hard error.
# --------------------------------------------------------------------------
TEAM_WHITELIST = [
    "Dir.isign",
    "intPerimeter", "intLeftEnd", "intRightEnd", "intCommonEnd",
    "gap", "sepRate", "Approaching", "meetTime",
    "AtLeftBorder", "AtRightBorder", "CoLocated", "Escorting", "AtSeparation",
    "separationTime", "borderTime", "droneNextTime",
    "SepRight", "SepLeft", "MeetRight", "MeetLeft",
    "escortDir", "escortDirLeft", "newDir",
]

# Lean name -> Verus name.
TEAM_RENAME = {
    "Dir.isign": "isign",
    "intPerimeter": "perimeter", "intLeftEnd": "left_end",
    "intRightEnd": "right_end", "intCommonEnd": "common_end",
    "gap": "gap", "sepRate": "sep_rate", "Approaching": "approaching",
    "meetTime": "meet_time",
    "AtLeftBorder": "at_left_border", "AtRightBorder": "at_right_border",
    "CoLocated": "co_located", "Escorting": "escorting",
    "AtSeparation": "at_separation",
    "separationTime": "separation_time", "borderTime": "border_time",
    "droneNextTime": "drone_next_time",
    "SepRight": "sep_right", "SepLeft": "sep_left",
    "MeetRight": "meet_right", "MeetLeft": "meet_left",
    "escortDir": "escort_dir", "escortDirLeft": "escort_dir_left",
    "newDir": "new_dir",
}

# The drone-level half (S6a/S6d). These are the predicates a wrong transcription
# would hide in: `leg_ok` and `obs_ok` never execute, so nothing but this
# generator checks that the Verus ones say what the Lean ones say.
FENCE_WHITELIST = [
    "wf", "clearance", "fenceDir", "safe", "legOk", "obsOk", "trajStepOk",
]

FENCE_RENAME = {
    "wf": "wf", "clearance": "clearance", "fenceDir": "fence_dir",
    "safe": "safe", "legOk": "leg_ok", "obsOk": "obs_ok",
    "trajStepOk": "traj_step_ok",
}

# The pair and the link. `linkStepOk` and `driftOk` are NOT here: both subtract
# sample indices, which is ℕ subtraction in Lean (truncating) and `int`
# subtraction in Verus (not). They agree under the accompanying `src k ≤ k`, but
# a translator that mapped one to the other would be unsound in general, so they
# stay hand-written. `Dpss/SeparationInt.lean` says so at the top.
PAIR_WHITELIST = [
    "pairVehicle", "commsPairVehicle",
    "pairObsOk", "pairLegOk", "pairSafe", "pairTrajStepOk", "commsStepOk",
]

PAIR_RENAME = {
    "pairVehicle": "pair_vehicle", "commsPairVehicle": "comms_pair_vehicle",
    "pairObsOk": "pair_obs_ok", "pairLegOk": "pair_leg_ok",
    "pairSafe": "pair_safe", "pairTrajStepOk": "pair_traj_step_ok",
    "commsStepOk": "comms_step_ok",
}

# Postfix projections, written `(e).name` in Lean, that become a call in Verus.
PROJ = {".isign": "isign"}

# Lean expression atoms that map to a fixed Verus expression.
ATOMS = {"Dir.left": "Dir::Left", "Dir.right": "Dir::Right"}

# The team model reads the configuration's own fields as bare names.
TEAM_ATOMS = {**ATOMS, "left": "Dir::Left", "right": "Dir::Right",
              "K": "c.k", "n": "c.n"}

RESULT_TYPE = {"ℤ": "int", "Bool": "bool", "Dir": "Dir", "Prop": "bool",
               "Vehicle": "Vehicle"}

# Structures Lean writes as `⟨a, b, c⟩` and Verus as `T { f: a, g: b, h: c }`.
# The field order is the declaration order and is checked against the Lean source
# nowhere, which is exactly why there is only one entry: add a second only with
# the declaration in front of you.
STRUCTS = {"Vehicle": ["dmax", "turn", "eps"]}

# Lean binder type -> Verus parameter type, for the explicitly-parameterized half.
PARAM_TYPE = {"ℤ": "int", "ℕ": "nat", "Bool": "bool", "Dir": "Dir",
              "Vehicle": "Vehicle"}

# Words that end an application rather than continuing it. Without this,
# `if c.dir i = Dir.left then ...` parses `then` as an argument of `Dir.left`.
KEYWORDS = {"if", "then", "else", "match", "with", "fun", "do"}

# Terms that exist only to carry a proof. Lean threads `i.val + 1 < n` through the
# model as an explicit argument; Verus indices are plain `int` and carry no such
# obligation, so these are dropped rather than translated.
PROOF_HEADS = {"Config.prevIdx_lt", "Config.nextIdx_lt"}
PROOF = "_PROOF_"


class Refused(Exception):
    """The grammar does not cover this. Say so loudly; never guess."""


# --------------------------------------------------------------------------
# Reading the Lean
# --------------------------------------------------------------------------
def strip_comments(src: str) -> str:
    out, i, depth = [], 0, 0
    while i < len(src):
        if src.startswith("/-", i):
            depth += 1; i += 2; continue
        if depth and src.startswith("-/", i):
            depth -= 1; i += 2; continue
        if depth == 0 and src.startswith("--", i):
            j = src.find("\n", i)
            i = len(src) if j < 0 else j
            continue
        out.append(src[i] if depth == 0 or src[i] == "\n" else " ")
        i += 1
    return "".join(out)


DEF = re.compile(
    r"^def\s+([A-Za-z_][\w'.]*)\s*(.*?):\s*(ℤ|ℕ|Bool|Dir|Prop|Vehicle)\s*:=\s*(.*)$")


ISIGN = re.compile(
    r"^def\s+isign\s*:\s*Dir\s*→\s*ℤ\s*$", re.M)


def read_isign(code_lines):
    """`Dir.isign` is written as pattern-matching equations, not `name := body`."""
    for idx, line in enumerate(code_lines):
        if ISIGN.match(line.strip()):
            arms = []
            j = idx + 1
            while j < len(code_lines) and code_lines[j].strip().startswith("|"):
                arms.append(code_lines[j].strip())
                j += 1
            return idx + 1, "", "ℤ", " ".join(arms)
    return None


def read_defs(src: pathlib.Path, whitelist):
    """name -> (line, params, result type, body). Namespace-qualified where needed."""
    text = src.read_text(encoding="utf-8")
    code = strip_comments(text).splitlines()
    defs, ns = {}, []
    isign = read_isign(code)
    if isign:
        defs["Dir.isign"] = isign
    i = 0
    while i < len(code):
        raw = code[i]
        st = raw.strip()
        m = re.match(r"^namespace\s+([\w.]+)", st)
        if m:
            ns.append(m.group(1)); i += 1; continue
        if re.match(r"^end\s+[\w.]+", st):
            if ns: ns.pop()
            i += 1; continue
        m, i_body = DEF.match(st), i
        if not m and st.startswith("def "):
            # a signature wrapped over several lines: join until `:=` closes it
            joined, j = st, i + 1
            while j < len(code) and ":=" not in joined and j - i <= 4:
                if not code[j].startswith(" "):
                    break
                joined = joined + " " + code[j].strip()
                j += 1
            m = DEF.match(joined)
            if m:
                st, i_body = joined, j - 1
        if not m:
            i += 1; continue
        name, params, ty, first = m.groups()
        body = [first]
        j = (i_body + 1) if st != raw.strip() else (i + 1)
        while j < len(code):
            nxt = code[j]
            if nxt.strip() == "":
                j += 1; continue
            if not nxt.startswith(" "):
                break
            if DEF.match(nxt.strip()) or re.match(r"^(theorem|def|@\[)", nxt.strip()):
                break
            body.append(nxt.strip())
            j += 1
        qual = name if "." in name else ".".join(ns[1:] + [name]) if len(ns) > 1 else name
        short = name.split(".")[-1]
        key = name if name in whitelist else short
        defs[key] = (i + 1, params.strip(), ty, " ".join(body).strip())
        i = j
    return defs


# --------------------------------------------------------------------------
# Tokenizing and parsing the restricted expression grammar
# --------------------------------------------------------------------------
TOKEN = re.compile(r"""
    (?P<ws>\s+)
  | (?P<num>\d+)
  | (?P<ty>ℤ|ℕ)
  | (?P<id>[A-Za-z_][\w'.]*)
  | (?P<proj>\.[A-Za-z_]\w*)
  | (?P<op>==|&&|\|\||≤|≥|<|>|\+|-|\*|/|!|\(|\)|,|:|=>|\||=|→|∧|∨|¬|⟨|⟩)
""", re.X)


def tokenize(expr: str, where: str):
    toks, i = [], 0
    while i < len(expr):
        m = TOKEN.match(expr, i)
        if not m:
            raise Refused(f"{where}: cannot tokenize at {expr[i:i+30]!r}")
        i = m.end()
        if m.lastgroup == "ws":
            continue
        toks.append((m.lastgroup, m.group()))
    return toks


class Parser:
    """Precedence-climbing over the subset `Dpss/IntModel.lean` actually uses."""

    # (lean op, verus op, precedence, right-associative)
    BINOPS = [
        ("→", "==>", 0, True),
        ("||", "||", 1, False), ("∨", "||", 1, False),
        ("&&", "&&", 2, False), ("∧", "&&", 2, False),
        ("==", "==", 3, False), ("=", "==", 3, False),
        ("<", "<", 4, False), ("≤", "<=", 4, False),
        (">", ">", 4, False), ("≥", ">=", 4, False),
        ("+", "+", 5, False), ("-", "-", 5, False),
        ("*", "*", 6, False), ("/", "/", 6, False),
    ]

    def __init__(self, toks, where, known, mode="config", params=(), result=None):
        self.toks, self.i, self.where, self.known = toks, 0, where, known
        self.mode, self.params, self.result = mode, set(params), result
        self.atoms = TEAM_ATOMS if mode == "config" else ATOMS

    def peek(self):
        return self.toks[self.i] if self.i < len(self.toks) else (None, None)

    def take(self, val=None):
        k, v = self.peek()
        if val is not None and v != val:
            raise Refused(f"{self.where}: expected {val!r}, found {v!r}")
        self.i += 1
        return v

    def parse(self):
        e = self.expr(0)
        if self.i != len(self.toks):
            raise Refused(f"{self.where}: trailing {self.toks[self.i:][:4]!r}")
        return e

    def expr(self, minp):
        lhs = self.unary()
        while True:
            _, v = self.peek()
            hit = next((b for b in self.BINOPS if b[0] == v), None)
            if hit is None or hit[2] < minp:
                return lhs
            self.take()
            rhs = self.expr(hit[2] if hit[3] else hit[2] + 1)
            lhs = f"({lhs} {hit[1]} {rhs})"

    def unary(self):
        k, v = self.peek()
        if v in ("!", "¬"):
            self.take(); return f"!{self.unary()}"
        if v == "-":
            self.take(); return f"(-{self.unary()})"
        return self.app()

    def app(self):
        head = self.postfix(self.atom())
        args = []
        while True:
            k, v = self.peek()
            if k == "id" and v in KEYWORDS:
                break
            if k in ("id", "num") or v == "(":
                args.append(self.postfix(self.atom()))
            else:
                break
        if not args:
            return head
        return self.call(head, args)

    def call(self, head, args):
        if self.mode == "explicit":
            return self.call_explicit(head, args)
        # `min a b`
        if head == "min":
            if len(args) != 2:
                raise Refused(f"{self.where}: min takes two arguments")
            return f"vstd::math::min({args[0]}, {args[1]})"
        # field access written as application: `c.pos i`, `c.dir i`
        if head in ("c.pos", "c.dir"):
            if len(args) != 1:
                raise Refused(f"{self.where}: {head} takes one index")
            return f"{head.replace('c.', 'c.')}[{args[0]}]"
        # a proof term -- carries no computational content
        if head in PROOF_HEADS:
            return PROOF
        # index arithmetic
        if head == "Config.nextIdx":
            return f"({args[0]} + 1)"
        if head == "Config.prevIdx":
            return f"({args[0]} - 1)"
        # a call to another translated definition
        base = head.split(".")[-1]
        if base in self.known:
            passed = [a for a in args
                      if a not in ("c.k", "c.n", PROOF) and a != "h"]
            inner = ", ".join(["c"] + passed) if base != "isign" else ", ".join(passed)
            return f"{self.known[base]}({inner})"
        raise Refused(f"{self.where}: unknown function {head!r}")

    def call_explicit(self, head, args):
        """The drone-level half passes its arguments explicitly, so a call is a
        call. The one wrinkle is Lean's dot notation: `v.clearance d` is
        `clearance(v, d)`, because `Vehicle` is a plain struct in Verus and its
        specification functions are free functions."""
        if head == "min":
            if len(args) != 2:
                raise Refused(f"{self.where}: min takes two arguments")
            return f"vstd::math::min({args[0]}, {args[1]})"
        if "." in head:
            recv, fld = head.rsplit(".", 1)
            if fld in self.known and recv.split(".")[0] in self.params:
                # Lean's dot notation: `v.clearance d` is `clearance(v, d)`
                return f"{self.known[fld]}({', '.join([snake(recv)] + args)})"
            if fld in self.known:
                # a namespace-qualified call: `Vehicle.clearance v d`
                return f"{self.known[fld]}({', '.join(args)})"
            raise Refused(f"{self.where}: unknown projection or call {head!r}")
        if head in self.known:
            return f"{self.known[head]}({', '.join(args)})"
        raise Refused(f"{self.where}: unknown function {head!r}")

    def postfix(self, e):
        """`(c.dir i).isign` -- a projection Lean writes postfix and Verus calls."""
        while self.peek()[0] == "proj":
            pr = self.take()
            if pr not in PROJ:
                raise Refused(f"{self.where}: unknown projection {pr!r}")
            e = f"{PROJ[pr]}({e})"
        return e

    def atom(self):
        k, v = self.peek()
        if v == "⟨":
            return self.anon()
        if v == "(":
            self.take("(")
            # a type ascription `(x : ℤ)` is a cast, and every numeric type here
            # is `int` in Verus, so it is a no-op
            inner = self.expr(0)
            if self.peek()[1] == ":":
                self.take(":"); self.take()
            self.take(")")
            # a parenthesised proof term is still a proof term
            return PROOF if inner == PROOF else f"({inner})"
        if k == "num":
            return self.take()
        if k == "id":
            name = self.take()
            if name == "if":
                return self.ite()
            if name in self.atoms:
                return self.atoms[name]
            if self.mode == "explicit":
                return self.atom_explicit(name)
            # the configuration's fields; `c.pos`/`c.dir` are applied to an index
            # by `call`, `c.time` stands alone
            if name in ("c.pos", "c.dir", "c.time"):
                return name
            # heads that `call` knows how to apply
            if name in ("min", "Config.nextIdx", "Config.prevIdx") or name in PROOF_HEADS:
                return name
            if re.fullmatch(r"[a-z][\w']*", name) or name in ("min",):
                if name.endswith(".val"):
                    return name[: -len(".val")]
                return name
            if name.endswith(".val"):
                return name[: -len(".val")]
            if name in self.known or name.split(".")[-1] in self.known:
                return name
            raise Refused(f"{self.where}: unknown identifier {name!r}")
        raise Refused(f"{self.where}: unexpected token {v!r}")

    def anon(self):
        """`⟨a, b, c⟩` — Lean's anonymous constructor. Which structure it builds
        is the definition's result type, and the field names come from `STRUCTS`;
        anything else is refused."""
        if self.result not in STRUCTS:
            raise Refused(f"{self.where}: ⟨…⟩ but the result type "
                          f"{self.result!r} is not a known structure")
        fields = STRUCTS[self.result]
        self.take("⟨")
        args = [self.expr(0)]
        while self.peek()[1] == ",":
            self.take(",")
            args.append(self.expr(0))
        self.take("⟩")
        if len(args) != len(fields):
            raise Refused(f"{self.where}: {self.result} takes {len(fields)} "
                          f"fields, found {len(args)}")
        body = ", ".join(f"{f}: {a}" for f, a in zip(fields, args))
        return f"{self.result} {{ {body} }}"

    def atom_explicit(self, name):
        """A bare name is a binder, a field of one, or a function about to be
        applied. Anything else is refused."""
        if name in self.params:
            return snake(name)
        if "." in name:
            recv, fld = name.split(".", 1)
            if recv in self.params:
                if "." in fld:
                    raise Refused(f"{self.where}: nested projection {name!r}")
                return f"{snake(recv)}.{snake(fld)}"
            if name.rsplit(".", 1)[1] in self.known:
                return name
            raise Refused(f"{self.where}: unknown identifier {name!r}")
        if name in self.known or name == "min":
            return name
        raise Refused(f"{self.where}: unknown identifier {name!r}")

    def ite(self):
        """`if c then a else b` and `if h : c then a else b` (dite)."""
        save = self.i
        k, v = self.peek()
        if k == "id" and self.toks[self.i + 1][1] == ":" if self.i + 1 < len(self.toks) else False:
            self.take()  # the proof binder name
            self.take(":")
        cond = self.expr(0)
        self.take("then")
        a = self.expr(0)
        self.take("else")
        b = self.expr(0)
        return f"if {cond} {{ {a} }} else {{ {b} }}"


# --------------------------------------------------------------------------
# Emitting
# --------------------------------------------------------------------------
def snake(name: str) -> str:
    """`pNext` -> `p_next`. Lean names the arguments in camel case; Verus, like
    the rest of this crate, in snake."""
    return re.sub(r"(?<=[a-z0-9])([A-Z])", lambda m: "_" + m.group(1).lower(), name)


def verus_params(name, params):
    """Every spec fn takes the configuration; indices come through as `int`."""
    if name == "Dir.isign":
        return "d: Dir"
    ps = ["c: Snapshot"]
    if re.search(r"\(i\s*:\s*Fin", params):
        ps.append("i: int")
    return ", ".join(ps)


BINDER = re.compile(r"\(\s*([A-Za-z_][\w']*(?:\s+[A-Za-z_][\w']*)*)\s*:\s*([^)]+?)\s*\)")


def explicit_params(params: str, where: str):
    """Read `(v : Vehicle) (p : ℤ) (low pNext : ℤ)` into typed Verus binders.

    Refused rather than guessed at if a binder is implicit, dependent, or of a
    type the Verus side does not have."""
    out, names, pos = [], [], 0
    for m in BINDER.finditer(params):
        if params[pos:m.start()].strip():
            raise Refused(f"{where}: cannot read the binder at "
                          f"{params[pos:m.start()].strip()!r}")
        pos = m.end()
        ty = m.group(2).strip()
        if ty not in PARAM_TYPE:
            raise Refused(f"{where}: binder type {ty!r} has no Verus counterpart")
        for nm in m.group(1).split():
            out.append(f"{snake(nm)}: {PARAM_TYPE[ty]}")
            names.append(nm)
    if params[pos:].strip():
        raise Refused(f"{where}: trailing binder {params[pos:].strip()!r}")
    return ", ".join(out), names


def translate_isign(body, where):
    """`Dir.isign` is a match, which the expression grammar does not cover."""
    m = re.search(r"\|\s*left\s*=>\s*(-?\d+)\s*\|\s*right\s*=>\s*(-?\d+)", body)
    if not m:
        raise Refused(f"{where}: isign is not the expected two-arm match")
    return (f"match d {{ Dir::Left => {m.group(1)}int, "
            f"Dir::Right => {m.group(2)}int }}")


SOURCES = [
    dict(
        name="team",
        src=REPO / "Dpss" / "IntModel.lean",
        out=REPO / "rust" / "src" / "spec" / "model.rs",
        whitelist=TEAM_WHITELIST,
        rename=TEAM_RENAME,
        qual={name: f"DPSS.{name}" for name in TEAM_WHITELIST},
        mode="config",
        imports="use crate::dir::Dir;\nuse crate::snapshot::Snapshot;",
        note="""// What is deliberately NOT generated, and is hand-written in ../exec.rs and
// ../inv.rs instead: `advance`, `step`, `run` (structure literals and recursion),
// `timeToNextEvent` (a `Finset.inf'`), the four standing conditions (quantifiers
// with a dependent proof argument), and `Dir` itself.""",
        preamble="""// The translator is syntactic only. The one semantically interesting step of this
// port -- real numbers to integers -- is done and *proved* in Lean
// (`embed_step`, `intRun_converges`), not here.
//""",
    ),
    dict(
        name="fence",
        src=REPO / "Dpss" / "FenceInt.lean",
        out=REPO / "rust" / "src" / "spec" / "fence_model.rs",
        whitelist=FENCE_WHITELIST,
        rename=FENCE_RENAME,
        qual={"wf": "DPSS.FenceInt.Vehicle.wf",
              "clearance": "DPSS.FenceInt.Vehicle.clearance",
              "fenceDir": "DPSS.FenceInt.fenceDir",
              "safe": "DPSS.FenceInt.safe",
              "legOk": "DPSS.FenceInt.legOk",
              "obsOk": "DPSS.FenceInt.obsOk",
              "trajStepOk": "DPSS.FenceInt.trajStepOk"},
        mode="explicit",
        imports="use crate::dir::Dir;\nuse crate::vehicle::Vehicle;",
        note="""// What is deliberately NOT generated: `trajOk`, which quantifies over every
// sample -- the same exclusion the team model makes for its standing conditions
// -- and the `Vehicle` struct itself, which is hand-written in ../vehicle.rs as
// `Dir` and `Snapshot` are. `traj_ok` is assembled from `obs_ok`, `fence_dir` and
// `leg_ok` in ../fence.rs, so the predicates a wrong transcription would hide in
// are all below.""",
        preamble="""// These are the predicates that never execute, so nothing but this generator
// checks that the Verus ones say what the Lean ones say. The `_ex` functions of
// ../fence.rs are proved to compute them (S6b); this file is where they come
// from (S6d).
//
// No scaling argument is involved, unlike the team model: `Dpss/FenceInt.lean`
// states the fence over the same integers Verus has.
//""",
    ),
    dict(
        name="pair",
        src=REPO / "Dpss" / "SeparationInt.lean",
        out=REPO / "rust" / "src" / "spec" / "separation_model.rs",
        whitelist=PAIR_WHITELIST,
        rename=PAIR_RENAME,
        qual={name: f"DPSS.FenceInt.{name}" for name in PAIR_WHITELIST},
        mode="explicit",
        imports=("use crate::dir::Dir;\nuse crate::vehicle::Vehicle;\n"
                 "use crate::spec::fence_model::*;"),
        note="""// What is deliberately NOT generated: `link_ok`'s two index clauses. Both
// subtract sample indices, which in Lean is ℕ subtraction (truncating at zero)
// and in Verus is `int` subtraction (not). They agree under the `src(k) <= k`
// that `link_ok` itself states -- but a translator that mapped one to the other
// would be unsound in general, and this one refuses rather than guesses. They
// are hand-written in ../comms.rs, beside the Lean statement in
// `DPSS.Fence.CommsPair`.""",
        preamble="""// The pair and the link, at the same integers as the fence. Every predicate here
// is proved in Lean to be the corresponding fence predicate on the doubled
// vehicle (`pairLegOk_iff` and friends), which is the content of
// `PairTraj.toFence` -- the pair layer adds coordinates, not content.""",
        after="fence",
    ),
]


def generate(source, preknown=None) -> str | None:
    """The Verus text for one source, or None after printing why it was refused."""
    defs = read_defs(source["src"], source["whitelist"])
    known, out, missing = dict(preknown or {}), [], []
    src, rename, mode = source["src"], source["rename"], source["mode"]

    for lean in source["whitelist"]:
        key = lean if lean in defs else lean.split(".")[-1]
        if key not in defs:
            missing.append(lean)
            continue
        line, params, ty, body = defs[key]
        where = f"{lean} ({src.relative_to(REPO)}:{line})"
        vname = rename[lean]
        try:
            if lean == "Dir.isign":
                expr, binders = translate_isign(body, where), verus_params(lean, params)
            elif mode == "config":
                expr = Parser(tokenize(body, where), where, known).parse()
                binders = verus_params(lean, params)
            else:
                binders, names = explicit_params(params, where)
                expr = Parser(tokenize(body, where), where, known, mode, names,
                              ty).parse()
        except Refused as e:
            print(f"::error::REFUSED {e}", file=sys.stderr)
            print("The grammar does not cover this definition. Extend the grammar "
                  "deliberately, or hand-write it on the Rust side and remove it "
                  "from the whitelist -- do not let the translator guess.",
                  file=sys.stderr)
            return None
        known[lean.split(".")[-1]] = vname
        out.append(f"""/// `{source["qual"][lean]}` -- {src.relative_to(REPO)}:{line}
pub open spec fn {vname}({binders}) -> {RESULT_TYPE[ty]} {{
    {expr}
}}
""")

    if missing:
        print(f"::error::not found in {src.name}: {', '.join(missing)}",
              file=sys.stderr)
        return None

    return f'''// GENERATED by scripts/lean_to_verus.py -- DO NOT EDIT.
//
// Every function below is a mechanical transliteration of a definition in
// {src.relative_to(REPO)}, cited by file and line above each one. Regenerate with
//
//     python3 scripts/lean_to_verus.py
//
// CI regenerates and fails if this file has drifted, so it cannot silently rot.
//
{source["preamble"]}
{source["note"]}

use vstd::prelude::*;
{source["imports"]}

verus! {{

{"".join(out)}}} // verus!
'''


def main() -> int:
    check = "--check" in sys.argv
    rc = 0
    produced = {}
    for source in SOURCES:
        text = generate(source, produced.get(source.get("after")))
        produced[source["name"]] = {k.split(".")[-1]: v
                                    for k, v in source["rename"].items()}
        if text is None:
            return 1
        out, src = source["out"], source["src"]
        n = text.count("pub open spec fn")
        if check:
            cur = out.read_text(encoding="utf-8") if out.exists() else ""
            if cur != text:
                print(f"::error::{out.relative_to(REPO)} is stale; "
                      "run python3 scripts/lean_to_verus.py", file=sys.stderr)
                rc = 1
                continue
            print(f"{out.name} is current ({n} spec fns).")
            continue
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print(f"generated {out.relative_to(REPO)}: {n} spec fns "
              f"from {src.relative_to(REPO)}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
