#!/usr/bin/env python3
"""Generate the Verus specification from `Dpss/IntModel.lean`.

The Rust half must be checked against *the* specification, not against a second
one that somebody typed in again. So the scalar and boolean definitions of the
integer model are translated mechanically into Verus `spec fn`s, and the result is
checked in and re-generated by CI, which fails if it has drifted.

## What this is, and what it is not

It is a translator for **one file**, over a deliberately small grammar. It is not a
general Lean front end and must never be mistaken for one. Anything outside the
grammar is **refused with an error naming the definition and the token**, never
guessed at — a translator that quietly does its best is worse than no translator,
because the Rust would then verify beautifully against the wrong specification.

It is also *syntactic only*. The one semantically interesting step in this port —
real numbers to integers — happens in `Dpss/IntModel.lean`, where it is proved
(`embed_step`, `intRun_converges`). This script only changes notation.

## What it does not translate, and why

Four kinds of definition are hand-written on the Rust side instead, each citing its
Lean source:

* `advance`, `step`, `run` build a new configuration — structure literals and
  recursion, not arithmetic;
* `timeToNextEvent` is a `Finset.inf'` over `Fin n`;
* `OnPerimeter`, `AdjOrdered`, `EscortsCoherent`, `OnLattice` quantify over `Fin n`
  with a dependent proof argument;
* `Dir` itself is a Rust `enum`.

None of those is arithmetic, which is where a transcription error would hide. The
differential tests cover them end to end.

Usage: python3 scripts/lean_to_verus.py [--check]
"""
from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC = REPO / "Dpss" / "IntModel.lean"
OUT = REPO / "rust" / "src" / "spec" / "model.rs"

# --------------------------------------------------------------------------
# What to translate, in dependency order. A name not listed here is not emitted;
# a name listed here that cannot be parsed is a hard error.
# --------------------------------------------------------------------------
WHITELIST = [
    "Dir.isign",
    "intPerimeter", "intLeftEnd", "intRightEnd", "intCommonEnd",
    "gap", "sepRate", "Approaching", "meetTime",
    "AtLeftBorder", "AtRightBorder", "CoLocated", "Escorting", "AtSeparation",
    "separationTime", "borderTime", "droneNextTime",
    "SepRight", "SepLeft", "MeetRight", "MeetLeft",
    "escortDir", "escortDirLeft", "newDir",
]

# Lean name -> Verus name.
RENAME = {
    "Dir.isign": "isign",
    "intPerimeter": "perimeter", "intLeftEnd": "left_end",
    "intRightEnd": "right_end", "intCommonEnd": "common_end",
    "gap": "gap", "sepRate": "sep_rate", "Approaching": "approaching",
    "meetTime": "meet_time",
    "AtLeftBorder": "at_left_border", "AtRightBorder": "at_right_border",
    "CoLocated": "co_located", "Escorting": "escorting",
    "AtSeparation": "at_separation",
    "separationTime": "separation_time", "borderTime": "border_time",
    "droneNextTime": "drone_next_time",
    "SepRight": "sep_right", "SepLeft": "sep_left",
    "MeetRight": "meet_right", "MeetLeft": "meet_left",
    "escortDir": "escort_dir", "escortDirLeft": "escort_dir_left",
    "newDir": "new_dir",
}

# Postfix projections, written `(e).name` in Lean, that become a call in Verus.
PROJ = {".isign": "isign"}

# Lean expression atoms that map to a fixed Verus expression.
ATOMS = {
    "Dir.left": "Dir::Left", "Dir.right": "Dir::Right",
    "left": "Dir::Left", "right": "Dir::Right",
    "K": "c.k", "n": "c.n",
}

RESULT_TYPE = {"ℤ": "int", "Bool": "bool", "Dir": "Dir"}

# Words that end an application rather than continuing it. Without this,
# `if c.dir i = Dir.left then ...` parses `then` as an argument of `Dir.left`.
KEYWORDS = {"if", "then", "else", "match", "with", "fun", "do"}

# Terms that exist only to carry a proof. Lean threads `i.val + 1 < n` through the
# model as an explicit argument; Verus indices are plain `int` and carry no such
# obligation, so these are dropped rather than translated.
PROOF_HEADS = {"Config.prevIdx_lt", "Config.nextIdx_lt"}
PROOF = "_PROOF_"


class Refused(Exception):
    """The grammar does not cover this. Say so loudly; never guess."""


# --------------------------------------------------------------------------
# Reading the Lean
# --------------------------------------------------------------------------
def strip_comments(src: str) -> str:
    out, i, depth = [], 0, 0
    while i < len(src):
        if src.startswith("/-", i):
            depth += 1; i += 2; continue
        if depth and src.startswith("-/", i):
            depth -= 1; i += 2; continue
        if depth == 0 and src.startswith("--", i):
            j = src.find("\n", i)
            i = len(src) if j < 0 else j
            continue
        out.append(src[i] if depth == 0 or src[i] == "\n" else " ")
        i += 1
    return "".join(out)


DEF = re.compile(r"^def\s+([A-Za-z_][\w'.]*)\s*(.*?):\s*(ℤ|Bool|Dir)\s*:=\s*(.*)$")


ISIGN = re.compile(
    r"^def\s+isign\s*:\s*Dir\s*→\s*ℤ\s*$", re.M)


def read_isign(code_lines):
    """`Dir.isign` is written as pattern-matching equations, not `name := body`."""
    for idx, line in enumerate(code_lines):
        if ISIGN.match(line.strip()):
            arms = []
            j = idx + 1
            while j < len(code_lines) and code_lines[j].strip().startswith("|"):
                arms.append(code_lines[j].strip())
                j += 1
            return idx + 1, "", "ℤ", " ".join(arms)
    return None


def read_defs():
    """name -> (line, params, result type, body). Namespace-qualified where needed."""
    text = SRC.read_text(encoding="utf-8")
    code = strip_comments(text).splitlines()
    defs, ns = {}, []
    isign = read_isign(code)
    if isign:
        defs["Dir.isign"] = isign
    i = 0
    while i < len(code):
        raw = code[i]
        st = raw.strip()
        m = re.match(r"^namespace\s+([\w.]+)", st)
        if m:
            ns.append(m.group(1)); i += 1; continue
        if re.match(r"^end\s+[\w.]+", st):
            if ns: ns.pop()
            i += 1; continue
        m = DEF.match(st)
        if not m:
            i += 1; continue
        name, params, ty, first = m.groups()
        body = [first]
        j = i + 1
        while j < len(code):
            nxt = code[j]
            if nxt.strip() == "":
                j += 1; continue
            if not nxt.startswith(" "):
                break
            if DEF.match(nxt.strip()) or re.match(r"^(theorem|def|@\[)", nxt.strip()):
                break
            body.append(nxt.strip())
            j += 1
        qual = name if "." in name else ".".join(ns[1:] + [name]) if len(ns) > 1 else name
        short = name.split(".")[-1]
        key = name if name in WHITELIST else short
        defs[key] = (i + 1, params.strip(), ty, " ".join(body).strip())
        i = j
    return defs


# --------------------------------------------------------------------------
# Tokenizing and parsing the restricted expression grammar
# --------------------------------------------------------------------------
TOKEN = re.compile(r"""
    (?P<ws>\s+)
  | (?P<num>\d+)
  | (?P<ty>ℤ|ℕ)
  | (?P<id>[A-Za-z_][\w'.]*)
  | (?P<proj>\.[A-Za-z_]\w*)
  | (?P<op>==|&&|\|\||≤|≥|<|>|\+|-|\*|/|!|\(|\)|,|:|=>|\||=)
""", re.X)


def tokenize(expr: str, where: str):
    toks, i = [], 0
    while i < len(expr):
        m = TOKEN.match(expr, i)
        if not m:
            raise Refused(f"{where}: cannot tokenize at {expr[i:i+30]!r}")
        i = m.end()
        if m.lastgroup == "ws":
            continue
        toks.append((m.lastgroup, m.group()))
    return toks


class Parser:
    """Precedence-climbing over the subset `Dpss/IntModel.lean` actually uses."""

    # (lean op, verus op, precedence)
    BINOPS = [
        ("||", "||", 1), ("&&", "&&", 2),
        ("==", "==", 3), ("=", "==", 3),
        ("<", "<", 4), ("≤", "<=", 4), (">", ">", 4), ("≥", ">=", 4),
        ("+", "+", 5), ("-", "-", 5),
        ("*", "*", 6), ("/", "/", 6),
    ]

    def __init__(self, toks, where, known):
        self.toks, self.i, self.where, self.known = toks, 0, where, known

    def peek(self):
        return self.toks[self.i] if self.i < len(self.toks) else (None, None)

    def take(self, val=None):
        k, v = self.peek()
        if val is not None and v != val:
            raise Refused(f"{self.where}: expected {val!r}, found {v!r}")
        self.i += 1
        return v

    def parse(self):
        e = self.expr(0)
        if self.i != len(self.toks):
            raise Refused(f"{self.where}: trailing {self.toks[self.i:][:4]!r}")
        return e

    def expr(self, minp):
        lhs = self.unary()
        while True:
            _, v = self.peek()
            hit = next((b for b in self.BINOPS if b[0] == v), None)
            if hit is None or hit[2] < minp:
                return lhs
            self.take()
            rhs = self.expr(hit[2] + 1)
            lhs = f"({lhs} {hit[1]} {rhs})"

    def unary(self):
        k, v = self.peek()
        if v == "!":
            self.take(); return f"!{self.unary()}"
        if v == "-":
            self.take(); return f"(-{self.unary()})"
        return self.app()

    def app(self):
        head = self.postfix(self.atom())
        args = []
        while True:
            k, v = self.peek()
            if k == "id" and v in KEYWORDS:
                break
            if k in ("id", "num") or v == "(":
                args.append(self.postfix(self.atom()))
            else:
                break
        if not args:
            return head
        return self.call(head, args)

    def call(self, head, args):
        # `min a b`
        if head == "min":
            if len(args) != 2:
                raise Refused(f"{self.where}: min takes two arguments")
            return f"vstd::math::min({args[0]}, {args[1]})"
        # field access written as application: `c.pos i`, `c.dir i`
        if head in ("c.pos", "c.dir"):
            if len(args) != 1:
                raise Refused(f"{self.where}: {head} takes one index")
            return f"{head.replace('c.', 'c.')}[{args[0]}]"
        # a proof term -- carries no computational content
        if head in PROOF_HEADS:
            return PROOF
        # index arithmetic
        if head == "Config.nextIdx":
            return f"({args[0]} + 1)"
        if head == "Config.prevIdx":
            return f"({args[0]} - 1)"
        # a call to another translated definition
        base = head.split(".")[-1]
        if base in self.known:
            passed = [a for a in args
                      if a not in ("c.k", "c.n", PROOF) and a != "h"]
            inner = ", ".join(["c"] + passed) if base != "isign" else ", ".join(passed)
            return f"{self.known[base]}({inner})"
        raise Refused(f"{self.where}: unknown function {head!r}")

    def postfix(self, e):
        """`(c.dir i).isign` -- a projection Lean writes postfix and Verus calls."""
        while self.peek()[0] == "proj":
            pr = self.take()
            if pr not in PROJ:
                raise Refused(f"{self.where}: unknown projection {pr!r}")
            e = f"{PROJ[pr]}({e})"
        return e

    def atom(self):
        k, v = self.peek()
        if v == "(":
            self.take("(")
            # a type ascription `(x : ℤ)` is a cast, and every numeric type here
            # is `int` in Verus, so it is a no-op
            inner = self.expr(0)
            if self.peek()[1] == ":":
                self.take(":"); self.take()
            self.take(")")
            # a parenthesised proof term is still a proof term
            return PROOF if inner == PROOF else f"({inner})"
        if k == "num":
            return self.take()
        if k == "id":
            name = self.take()
            if name == "if":
                return self.ite()
            if name in ATOMS:
                return ATOMS[name]
            # the configuration's fields; `c.pos`/`c.dir` are applied to an index
            # by `call`, `c.time` stands alone
            if name in ("c.pos", "c.dir", "c.time"):
                return name
            # heads that `call` knows how to apply
            if name in ("min", "Config.nextIdx", "Config.prevIdx") or name in PROOF_HEADS:
                return name
            if re.fullmatch(r"[a-z][\w']*", name) or name in ("min",):
                if name.endswith(".val"):
                    return name[: -len(".val")]
                return name
            if name.endswith(".val"):
                return name[: -len(".val")]
            if name in self.known or name.split(".")[-1] in self.known:
                return name
            raise Refused(f"{self.where}: unknown identifier {name!r}")
        raise Refused(f"{self.where}: unexpected token {v!r}")

    def ite(self):
        """`if c then a else b` and `if h : c then a else b` (dite)."""
        save = self.i
        k, v = self.peek()
        if k == "id" and self.toks[self.i + 1][1] == ":" if self.i + 1 < len(self.toks) else False:
            self.take()  # the proof binder name
            self.take(":")
        cond = self.expr(0)
        self.take("then")
        a = self.expr(0)
        self.take("else")
        b = self.expr(0)
        return f"if {cond} {{ {a} }} else {{ {b} }}"


# --------------------------------------------------------------------------
# Emitting
# --------------------------------------------------------------------------
def verus_params(name, params):
    """Every spec fn takes the configuration; indices come through as `int`."""
    if name == "Dir.isign":
        return "d: Dir"
    ps = ["c: View"]
    if re.search(r"\(i\s*:\s*Fin", params):
        ps.append("i: int")
    return ", ".join(ps)


def translate_isign(body, where):
    """`Dir.isign` is a match, which the expression grammar does not cover."""
    m = re.search(r"\|\s*left\s*=>\s*(-?\d+)\s*\|\s*right\s*=>\s*(-?\d+)", body)
    if not m:
        raise Refused(f"{where}: isign is not the expected two-arm match")
    return (f"match d {{ Dir::Left => {m.group(1)}int, "
            f"Dir::Right => {m.group(2)}int }}")


def main() -> int:
    check = "--check" in sys.argv
    defs = read_defs()
    known, out, missing = {}, [], []

    for lean in WHITELIST:
        key = lean if lean in defs else lean.split(".")[-1]
        if key not in defs:
            missing.append(lean)
            continue
        line, params, ty, body = defs[key]
        where = f"{lean} (Dpss/IntModel.lean:{line})"
        vname = RENAME[lean]
        try:
            if lean == "Dir.isign":
                expr = translate_isign(body, where)
            else:
                expr = Parser(tokenize(body, where), where, known).parse()
        except Refused as e:
            print(f"::error::REFUSED {e}", file=sys.stderr)
            print("The grammar does not cover this definition. Extend the grammar "
                  "deliberately, or hand-write it on the Rust side and remove it "
                  "from WHITELIST -- do not let the translator guess.",
                  file=sys.stderr)
            return 1
        known[lean.split(".")[-1]] = vname
        out.append(f"""/// `DPSS.{lean}` -- {SRC.relative_to(REPO)}:{line}
pub open spec fn {vname}({verus_params(lean, params)}) -> {RESULT_TYPE[ty]} {{
    {expr}
}}
""")

    if missing:
        print(f"::error::not found in {SRC.name}: {', '.join(missing)}", file=sys.stderr)
        return 1

    header = f'''// GENERATED by scripts/lean_to_verus.py -- DO NOT EDIT.
//
// Every function below is a mechanical transliteration of a definition in
// {SRC.relative_to(REPO)}, cited by file and line above each one. Regenerate with
//
//     python3 scripts/lean_to_verus.py
//
// CI regenerates and fails if this file has drifted, so it cannot silently rot.
//
// The translator is syntactic only. The one semantically interesting step of this
// port -- real numbers to integers -- is done and *proved* in Lean
// (`embed_step`, `intRun_converges`), not here.
//
// What is deliberately NOT generated, and is hand-written in ../exec.rs and
// ../inv.rs instead: `advance`, `step`, `run` (structure literals and recursion),
// `timeToNextEvent` (a `Finset.inf'`), the four standing conditions (quantifiers
// with a dependent proof argument), and `Dir` itself.

use vstd::prelude::*;
use crate::dir::Dir;
use crate::view::View;

verus! {{

{"".join(out)}}} // verus!
'''
    if check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != header:
            print("::error::rust/src/spec/model.rs is stale; "
                  "run python3 scripts/lean_to_verus.py", file=sys.stderr)
            return 1
        print(f"model.rs is current ({len(out)} spec fns).")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="utf-8")
    print(f"generated {OUT.relative_to(REPO)}: {len(out)} spec fns "
          f"from {SRC.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
